name: 'Geol Action'
description: 'Installs [geol](https://github.com/opt-nc/geol) in a GitHub Actions workflow.'
branding :
  icon : 'calendar'
  color : 'green'

inputs:
  version:
    description: 'The version of geol to install. Defaults to "latest".'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install geol
      shell: bash
      run: curl -fsSL https://raw.githubusercontent.com/opt-nc/geol/main/install.sh | bash -s ${{ inputs.version }}