#!/usr/bin/env bash
# Runs `geol check`, builds a clean Markdown report from its JSON output,
# and (optionally) creates or updates a GitHub issue with the result.
set -uo pipefail

FILE="${GEOL_FILE:-.geol.yaml}"
DATE="${GEOL_DATE:-}"
STRICT="${GEOL_STRICT:-false}"
ISSUE_TITLE_DEFAULT='EOL report - {{app_name}}'
ISSUE_TITLE_TEMPLATE="${GEOL_ISSUE_TITLE:-$ISSUE_TITLE_DEFAULT}"
EOL_LABEL="${GEOL_EOL_LABEL:-eol}"
WARNING_LABEL="${GEOL_WARNING_LABEL:-eol:warning}"
EXTRA_LABELS="${GEOL_EXTRA_LABELS:-}"
WARNING_THRESHOLD_DAYS="${GEOL_WARNING_THRESHOLD_DAYS:-90}"

FATAL_LABEL="${GEOL_FATAL_LABEL:-geol:error}"

CHECK_ARGS=(check --file "$FILE")
[ -n "$DATE" ] && CHECK_ARGS+=(--date "$DATE")
[ "$STRICT" = "true" ] && CHECK_ARGS+=(--strict)

REPORT_FILE="$(mktemp)"
ERR_LOG="$(mktemp)"
# The real Markdown report, exactly as geol produces it — this is what
# drives the exit code (and, in strict mode, the pass/fail decision).
geol "${CHECK_ARGS[@]}" > "$REPORT_FILE" 2>"$ERR_LOG"
CHECK_EXIT_CODE=$?

if [ ! -s "$REPORT_FILE" ]; then
  # geol produced no report at all: most likely a fatal error (e.g. an
  # invalid stack YAML file). Surface the "FTL" log line(s) and, when
  # possible, report it via a dedicated GitHub issue so it doesn't go
  # unnoticed.
  # Keep every ERR/FTL line (e.g. validation errors leading up to the final
  # fatal one), not just the last "FTL" line, so the root cause is visible.
  FATAL_LOG="$(grep -E 'ERR|FTL' "$ERR_LOG" || true)"
  [ -z "$FATAL_LOG" ] && FATAL_LOG="$(cat "$ERR_LOG")"
  [ -z "$FATAL_LOG" ] && FATAL_LOG="geol check produced no output (exit code ${CHECK_EXIT_CODE})."

  echo "::error::geol check failed: ${FATAL_LOG}"

  if [ -n "${GITHUB_TOKEN:-}" ]; then
    export GITHUB_TOKEN
    FILE_SLUG="$(basename "$FILE" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-' | sed 's/-\{2,\}/-/g; s/^-//; s/-$//')"
    ERROR_TRACKING_LABEL="geol-report:${FILE_SLUG:-config}-error"

    gh label create "$FATAL_LABEL" --color "b60205" 2>/dev/null || true
    gh label create "$ERROR_TRACKING_LABEL" --color "ededed" 2>/dev/null || true

    ERROR_BODY="$(cat <<EOF
<!-- geol-action-error:${FILE} -->
## ⚠️ geol check failed

geol was unable to produce a report for \`${FILE}\`. This usually means the stack configuration file is invalid.

\`\`\`
${FATAL_LOG}
\`\`\`

<sub>This report was automatically generated by [geol-action](https://github.com/opt-nc/geol-action).</sub>
EOF
)"
    EXISTING_ERROR_ISSUE="$(gh issue list --state open --label "$ERROR_TRACKING_LABEL" --json number --jq '.[0].number' 2>/dev/null || true)"
    if [ -n "$EXISTING_ERROR_ISSUE" ]; then
      gh issue comment "$EXISTING_ERROR_ISSUE" --body "$ERROR_BODY"
    else
      gh issue create --title "geol check error - ${FILE}" --body "$ERROR_BODY" --label "$FATAL_LABEL" --label "$ERROR_TRACKING_LABEL"
    fi
  fi

  rm -f "$REPORT_FILE" "$ERR_LOG"
  exit 1
fi
rm -f "$ERR_LOG"

# A second, JSON call (same args, minus --strict) only to extract structured
# metadata (score, per-component status/days) used to build the colored
# badges and the summary line — it never affects the exit code.
JSON_ARGS=(check --file "$FILE" --json)
[ -n "$DATE" ] && JSON_ARGS+=(--date "$DATE")
JSON_OUTPUT="$(geol "${JSON_ARGS[@]}" 2>/dev/null)"

APP_NAME="$(echo "$JSON_OUTPUT" | jq -r '.title // "stack"')"
SCORE_VALUE="$(echo "$JSON_OUTPUT" | jq -r '.score[0].value // "n/a"')"
TODAY="$(date -u +%Y-%m-%d)"

EOL_COUNT="$(echo "$JSON_OUTPUT" | jq '[.software_components[] | select(.status == "EOL")] | length')"
WARNING_COUNT="$(echo "$JSON_OUTPUT" | jq --argjson threshold "$WARNING_THRESHOLD_DAYS" \
  '[.software_components[] | select(.status != "EOL" and (.days | tonumber? // 99999) >= 0 and (.days | tonumber? // 99999) <= $threshold)] | length')"

# Components flagged with "always-latest: true" in the stack file (a policy
# marker, not exposed in geol's JSON output) that are not on their latest
# version, so we can name them explicitly in the summary.
ALWAYS_LATEST_NAMES="$(awk '
  /^[[:space:]]*-[[:space:]]*name:/ {
    name = $0
    sub(/^[[:space:]]*-[[:space:]]*name:[[:space:]]*/, "", name)
    gsub(/^"|"$|^\x27|\x27$/, "", name)
  }
  /always-latest:[[:space:]]*true/ { print name }
' "$FILE")"

NOT_LATEST_LIST=""
NOT_LATEST_COUNT=0
if [ -n "$ALWAYS_LATEST_NAMES" ]; then
  while IFS= read -r name; do
    [ -z "$name" ] && continue
    ENTRY="$(echo "$JSON_OUTPUT" | jq -r --arg name "$name" \
      '.software_components[] | select(.software == $name and .is_latest == false) | "\(.software) (\(.version) → \(.latest_version))"')"
    if [ -n "$ENTRY" ]; then
      NOT_LATEST_COUNT=$((NOT_LATEST_COUNT + 1))
      NOT_LATEST_LIST="${NOT_LATEST_LIST:+${NOT_LATEST_LIST}, }${ENTRY}"
    fi
  done <<< "$ALWAYS_LATEST_NAMES"
fi

# One colored pastille per software component, in the same order as the
# components appear in geol's own table, so it can be spliced into it.
ICONS_FILE="$(mktemp)"
echo "$JSON_OUTPUT" | jq -r --argjson threshold "$WARNING_THRESHOLD_DAYS" '
  .software_components[] | (
    ((.days | tonumber?) // null) as $d
    | if .status == "EOL" then "🔴"
      elif ($d != null and $d >= 0 and $d <= $threshold) then "🟡"
      else "🟢" end
  )' > "$ICONS_FILE"

# Splice the pastilles into the "Status" column of geol's real Markdown
# table, without altering anything else it produced.
REPORT_CONTENT="$(awk -F'|' -v OFS='|' -v icons_file="$ICONS_FILE" '
  BEGIN {
    i = 0
    while ((getline line < icons_file) > 0) { i++; icon[i] = line }
    n = i
    i = 0
  }
  /^$/ { insep = 0 }
  /^-+\|/ { insep = 1; print; next }
  insep && NF > 1 {
    i++
    if (i <= n) {
      gsub(/^[ \t]+|[ \t]+$/, "", $4)
      $4 = " " icon[i] " " $4 " "
    }
    print
    next
  }
  { print }
' "$REPORT_FILE")"
rm -f "$ICONS_FILE"

NOT_LATEST_SUFFIX=""
[ "$NOT_LATEST_COUNT" -gt 0 ] && NOT_LATEST_SUFFIX=", ${NOT_LATEST_COUNT} not on latest version (${NOT_LATEST_LIST})"

BODY_MARKER="<!-- geol-action-report:${APP_NAME} -->"
BODY="$(cat <<EOF
${BODY_MARKER}
**Generated:** ${TODAY} (via [geol](https://github.com/opt-nc/geol))
**Summary:** ${EOL_COUNT} past EOL, ${WARNING_COUNT} nearing EOL (≤ ${WARNING_THRESHOLD_DAYS} days)${NOT_LATEST_SUFFIX}

${REPORT_CONTENT}

<sub>This report was automatically generated by [geol-action](https://github.com/opt-nc/geol-action). A new comment will be added on each subsequent failing run.</sub>
EOF
)"
rm -f "$REPORT_FILE"

# Stable, exact-match label used to find the managed issue again on later runs.
# (Full-text body search is unreliable: search-index propagation delay and
# special characters like "<!--"/":" in the marker are not matched reliably.)
APP_SLUG="$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-' | sed 's/-\{2,\}/-/g; s/^-//; s/-$//')"
TRACKING_LABEL="geol-report:${APP_SLUG:-stack}"

echo "$JSON_OUTPUT" > /tmp/geol-check-result.json
{
  echo "eol-count=${EOL_COUNT}"
  echo "warning-count=${WARNING_COUNT}"
  echo "not-latest-count=${NOT_LATEST_COUNT}"
  echo "score=${SCORE_VALUE}"
} >> "${GITHUB_OUTPUT:-/dev/null}"

echo "## geol EOL report" >> "${GITHUB_STEP_SUMMARY:-/dev/null}"
echo "$BODY" >> "${GITHUB_STEP_SUMMARY:-/dev/null}"

if [ "$STRICT" = "true" ]; then
  if [ -z "${GITHUB_TOKEN:-}" ]; then
    echo "::error::'strict' is true but no github-token was provided, cannot manage the report issue."
    exit 1
  fi
  export GITHUB_TOKEN

  ISSUE_TITLE="${ISSUE_TITLE_TEMPLATE//\{\{app_name\}\}/${APP_NAME}}"
  ISSUE_TITLE="${ISSUE_TITLE//\{\{date\}\}/${TODAY}}"
  ISSUE_TITLE="${ISSUE_TITLE//\{\{score\}\}/${SCORE_VALUE}}"
  # Safety net: drop any unrecognized {{placeholder}} left in the title.
  ISSUE_TITLE="$(echo "$ISSUE_TITLE" | sed -E 's/\{\{[a-zA-Z0-9_]+\}\}//g')"

  LABELS=()
  if [ "$EOL_COUNT" -gt 0 ]; then
    LABELS+=("$EOL_LABEL")
  elif [ "$WARNING_COUNT" -gt 0 ]; then
    LABELS+=("$WARNING_LABEL")
  fi
  IFS=',' read -ra EXTRA_LABEL_ARR <<< "$EXTRA_LABELS"
  for l in "${EXTRA_LABEL_ARR[@]}"; do
    l_trimmed="$(echo "$l" | xargs)"
    [ -n "$l_trimmed" ] && LABELS+=("$l_trimmed")
  done
  LABELS+=("$TRACKING_LABEL")

  # Ensure labels exist (ignore errors if they already do).
  for l in "${LABELS[@]}"; do
    gh label create "$l" --color "ededed" 2>/dev/null || true
  done

  if [ "$CHECK_EXIT_CODE" -ne 0 ]; then
    EXISTING_ISSUE="$(gh issue list --state open --label "$TRACKING_LABEL" --json number --jq '.[0].number' 2>/dev/null || true)"
    LABEL_ARGS=()
    for l in "${LABELS[@]}"; do
      LABEL_ARGS+=(--add-label "$l")
    done
    if [ -n "$EXISTING_ISSUE" ]; then
      echo "Adding a new comment to existing issue #${EXISTING_ISSUE}"
      gh issue comment "$EXISTING_ISSUE" --body "$BODY"
      if [ "${#LABEL_ARGS[@]}" -gt 0 ]; then
        gh issue edit "$EXISTING_ISSUE" "${LABEL_ARGS[@]}"
      fi
    else
      echo "Creating new issue"
      CREATE_LABEL_ARGS=()
      for l in "${LABELS[@]}"; do
        CREATE_LABEL_ARGS+=(--label "$l")
      done
      gh issue create --title "$ISSUE_TITLE" --body "$BODY" "${CREATE_LABEL_ARGS[@]}"
    fi
  else
    echo "geol check --strict did not fail, no issue created."
    EXISTING_ISSUE="$(gh issue list --state open --label "$TRACKING_LABEL" --json number --jq '.[0].number' 2>/dev/null || true)"
    if [ -n "$EXISTING_ISSUE" ]; then
      echo "Closing previously open issue #${EXISTING_ISSUE}"
      gh issue close "$EXISTING_ISSUE" --comment "✅ Stack is now healthy, closing this report."
    fi
  fi
fi

exit "$CHECK_EXIT_CODE"
