#!/usr/bin/env bash
# Runs `geol check`, builds a clean Markdown report from its JSON output,
# and (optionally) creates or updates a GitHub issue with the result.
set -uo pipefail

FILE="${GEOL_FILE:-.geol.yaml}"
DATE="${GEOL_DATE:-}"
STRICT="${GEOL_STRICT:-false}"
CREATE_ISSUE="${GEOL_CREATE_ISSUE:-false}"
ISSUE_TITLE_TEMPLATE="${GEOL_ISSUE_TITLE:-EOL report - {{app_name}}}"
EOL_LABEL="${GEOL_EOL_LABEL:-eol}"
WARNING_LABEL="${GEOL_WARNING_LABEL:-eol:warning}"
EXTRA_LABELS="${GEOL_EXTRA_LABELS:-}"
WARNING_THRESHOLD_DAYS="${GEOL_WARNING_THRESHOLD_DAYS:-90}"

CHECK_ARGS=(check --file "$FILE" --json)
[ -n "$DATE" ] && CHECK_ARGS+=(--date "$DATE")
[ "$STRICT" = "true" ] && CHECK_ARGS+=(--strict)

JSON_OUTPUT="$(geol "${CHECK_ARGS[@]}")"
CHECK_EXIT_CODE=$?

if [ -z "$JSON_OUTPUT" ]; then
  echo "::error::geol check produced no output, aborting report generation."
  exit 1
fi

APP_NAME="$(echo "$JSON_OUTPUT" | jq -r '.title // "stack"')"
SCORE_VALUE="$(echo "$JSON_OUTPUT" | jq -r '.score[0].value // "n/a"')"
SCORE_MESSAGE="$(echo "$JSON_OUTPUT" | jq -r '.score[0].message // ""')"
TODAY="$(date -u +%Y-%m-%d)"

EOL_COUNT="$(echo "$JSON_OUTPUT" | jq '[.software_components[] | select(.status == "EOL")] | length')"
WARNING_COUNT="$(echo "$JSON_OUTPUT" | jq --argjson threshold "$WARNING_THRESHOLD_DAYS" \
  '[.software_components[] | select(.status != "EOL" and (.days | tonumber? // 99999) >= 0 and (.days | tonumber? // 99999) <= $threshold)] | length')"

# Build the Markdown table (no raw log lines, just clean data).
TABLE="$(echo "$JSON_OUTPUT" | jq -r --argjson threshold "$WARNING_THRESHOLD_DAYS" '
  ["| Status | Software | Version | EOL Date | Days | Latest |",
   "|---|---|---|---|---|---|"] +
  [.software_components[] | (
    ((.days | tonumber?) // null) as $d
    | (if .status == "EOL" then "🔴 EOL"
       elif ($d != null and $d >= 0 and $d <= $threshold) then "🟡 Soon"
       else "🟢 OK" end) as $icon
    | "| \($icon) | \(.software) | \(.version) | \(.eol_date // "-") | \(.days // "-") | \(.latest_version // "-") |"
  )] | .[]
')"

BODY_MARKER="<!-- geol-action-report:${APP_NAME} -->"
BODY="$(cat <<EOF
${BODY_MARKER}
## 📋 EOL stack report — ${APP_NAME}

**Score:** ${SCORE_VALUE}/100 — ${SCORE_MESSAGE}
**Generated:** ${TODAY} (via [geol](https://github.com/opt-nc/geol))
**Summary:** ${EOL_COUNT} past EOL, ${WARNING_COUNT} nearing EOL (≤ ${WARNING_THRESHOLD_DAYS} days)

${TABLE}

<sub>This issue was automatically generated by [geol-action](https://github.com/opt-nc/geol-action). It will be updated on the next run.</sub>
EOF
)"

echo "$JSON_OUTPUT" > /tmp/geol-check-result.json
{
  echo "eol-count=${EOL_COUNT}"
  echo "warning-count=${WARNING_COUNT}"
  echo "score=${SCORE_VALUE}"
} >> "${GITHUB_OUTPUT:-/dev/null}"

echo "## geol EOL report" >> "${GITHUB_STEP_SUMMARY:-/dev/null}"
echo "$BODY" >> "${GITHUB_STEP_SUMMARY:-/dev/null}"

if [ "$CREATE_ISSUE" = "true" ]; then
  if [ -z "${GITHUB_TOKEN:-}" ]; then
    echo "::error::'create-issue' is true but no github-token was provided."
    exit 1
  fi
  export GITHUB_TOKEN

  ISSUE_TITLE="${ISSUE_TITLE_TEMPLATE//\{\{app_name\}\}/${APP_NAME}}"
  ISSUE_TITLE="${ISSUE_TITLE//\{\{date\}\}/${TODAY}}"
  ISSUE_TITLE="${ISSUE_TITLE//\{\{score\}\}/${SCORE_VALUE}}"

  LABELS=()
  if [ "$EOL_COUNT" -gt 0 ]; then
    LABELS+=("$EOL_LABEL")
  elif [ "$WARNING_COUNT" -gt 0 ]; then
    LABELS+=("$WARNING_LABEL")
  fi
  IFS=',' read -ra EXTRA_LABEL_ARR <<< "$EXTRA_LABELS"
  for l in "${EXTRA_LABEL_ARR[@]}"; do
    l_trimmed="$(echo "$l" | xargs)"
    [ -n "$l_trimmed" ] && LABELS+=("$l_trimmed")
  done

  # Ensure labels exist (ignore errors if they already do).
  for l in "${LABELS[@]}"; do
    gh label create "$l" --color "ededed" 2>/dev/null || true
  done

  if [ "$EOL_COUNT" -gt 0 ] || [ "$WARNING_COUNT" -gt 0 ]; then
    EXISTING_ISSUE="$(gh issue list --state open --search "\"${BODY_MARKER}\" in:body" --json number --jq '.[0].number' 2>/dev/null || true)"
    LABEL_ARGS=()
    for l in "${LABELS[@]}"; do
      LABEL_ARGS+=(--add-label "$l")
    done
    if [ -n "$EXISTING_ISSUE" ]; then
      echo "Updating existing issue #${EXISTING_ISSUE}"
      gh issue edit "$EXISTING_ISSUE" --title "$ISSUE_TITLE" --body "$BODY" "${LABEL_ARGS[@]}"
    else
      echo "Creating new issue"
      CREATE_LABEL_ARGS=()
      for l in "${LABELS[@]}"; do
        CREATE_LABEL_ARGS+=(--label "$l")
      done
      gh issue create --title "$ISSUE_TITLE" --body "$BODY" "${CREATE_LABEL_ARGS[@]}"
    fi
  else
    echo "Stack is healthy, no issue created."
    EXISTING_ISSUE="$(gh issue list --state open --search "\"${BODY_MARKER}\" in:body" --json number --jq '.[0].number' 2>/dev/null || true)"
    if [ -n "$EXISTING_ISSUE" ]; then
      echo "Closing previously open issue #${EXISTING_ISSUE}"
      gh issue close "$EXISTING_ISSUE" --comment "✅ Stack is now healthy, closing this report."
    fi
  fi
fi

exit "$CHECK_EXIT_CODE"
