name: Test Geol Installation

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      
      - name: Install Geol
        uses: ./
        with:
          ref: 'main'
      
      - name: Verify Geol Installation
        run: |
          geol about
